name: "[AUTOMATICA] minha primeira ação mb"

on:
  push:
    branches:
      - main
      - master

jobs:
  meu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Primeiro Step
        run: >
          echo "🎉​ The job was automatically triggered by a event"
          echo "🐧 This job is now running on a server hosted by a Github!"

          echo 📅 Hoje é $(TZ="America/Sao_Paulo" date +"%d/%m/%Y %H:%M:%S")
          echo "Meu repositorio se chama: ${{ github.repository }}"
          ls -la
      - name: Git checkout (faz o clone do repo)
        uses: actions/checkout@v6

      - name: "Verifica se o repo foi baixado"
        run:  ls -la