on:
  push:

jobs:
  meu-job:
   runs-on: ubuntu-latest

  steps:
    - run: echo "🎉 Este Job foi executado automaticamente por um evento"
    - run: echo "🐧 Job está rodando em um servidor hospedado pelo GitHub!" 
    - run: ls -la

    - uses: actions/checkout@v6

    - run: ls -la
    
  segundo-job:
    runs-on: ubuntu-latest

    steps
      - run: echo Hoje é $(TZ-"America/Sao Paulo" date +"%d/%m/%Y %H:%M:%S")
      # - run: echo" Agore é $(time)"
    